# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new release build to the App Store"
  lane :release do
 get_certificates
    get_provisioning_profile
    increment_build_number(xcodeproj: "FutureDiary.xcodeproj")
    build_app(scheme: "FutureDiary")
    upload_to_app_store
slack(
      message: "Testflight 배포 성공",
      slack_url: "mosonleequestion.slack.com"
    )
  end

platform :ios do

  error do |lane, exception, options|
    slack(
      message: "에러 발생 : #{exception}",
      success: false,
      slack_url: "mosonleequestion.slack.com"
      )
  end
end
end
